Repository XgridInc/xc3, pull requests merged in 2023-06, with the labels that each got.

#19 Issue: Hotfix for Startup Script and Readme file
  README.md
  infrastructure/modules/serverless/cloudtrail.tf
  infrastructure/modules/xc3/README.md
  infrastructure/modules/xc3/cognito.tf
  infrastructure/modules/xc3/main.tf
  infrastructure/modules/xc3/startup-script.sh.tpl
  infrastructure/modules/xc3/variables.tf
Labels: bug, documentation, task

#27 Hotfix/v1.0.1: Hotfix in Documentation
  CHANGELOG.md
  README.md
  ROADMAP.md
Labels: enhancement, task

#30 Hotfix/v1.0.2: Hotfix in Development
  CHANGELOG.md
  README.md
  infrastructure/init.sh
  infrastructure/init_delete.sh
  infrastructure/main.tf
  infrastructure/modules/serverless/cloudtrail.tf
  infrastructure/modules/serverless/data.tf
  infrastructure/modules/serverless/variables.tf
  infrastructure/modules/xc3/data.tf
  infrastructure/modules/xc3/loadbalancer.tf
  infrastructure/modules/xc3/startup-script.sh.tpl
  infrastructure/modules/xc3/variables.tf
  infrastructure/terraform.auto.tfvars
  infrastructure/variables.tf
Labels: enhancement, task

#25 Add terraform.test.tfvars and other fixes
  infrastructure/init.sh
  infrastructure/init_delete.sh
  infrastructure/modules/xc3/README.md
  infrastructure/modules/xc3/main.tf
  infrastructure/modules/xc3/output.tf
  infrastructure/output.tf
  infrastructure/terraform.test.tfvars
Labels: task, feature_request

#34 Hotfix/v1.0.3: Updated the init.sh,config.sh and Readme
  README.md
  infrastructure/config.sh
  infrastructure/init.sh
  infrastructure/init_delete.sh
Labels: enhancement, task
