Repository XgridInc/xc3, pull requests merged in 2023-07, with the labels that each got.

#40 Title: Implement EIC Endpoint in our Internal AWS Account
  README.md
  infrastructure/modules/networking/security_groups.tf
  infrastructure/modules/xc3/README.md
  infrastructure/modules/xc3/main.tf
  infrastructure/modules/xc3/output.tf
  infrastructure/output.tf
Labels: task, feature_request

#47 Title : Env option for the Dev or Prod environment
  README.md
  infrastructure/main.tf
  infrastructure/modules/networking/security_groups.tf
  infrastructure/modules/networking/variables.tf
  infrastructure/modules/serverless/list_linked_accounts.tf
  infrastructure/modules/xc3/cognito.tf
  infrastructure/modules/xc3/data.tf
  infrastructure/modules/xc3/loadbalancer.tf
  infrastructure/modules/xc3/main.tf
  infrastructure/modules/xc3/output.tf
  infrastructure/modules/xc3/variables.tf
  infrastructure/output.tf
  infrastructure/terraform.auto.tfvars
  infrastructure/variables.tf
  init.sh
  input.sh
  pre_requirement/terraform.auto.tfvars
  src/organization/list_linked_accounts.py
Labels: enhancement, feature_request

#52 Hotfix/v1.1.0: Updated the Changelogfile
  CHANGELOG.md
  init.sh
Labels: enhancement, task
